<?php
/**
 * Generates a bootstrap in the module base directory (equivalent to the index.php) that defines the
 * koharnessed paths.
 *
 * @author    Andrew Coulton <andrew@ingenerator.com>
 * @copyright 2014 Kohana Team
 * @license    http://kohanaframework.org/license
 */
$template = <<<TEMPLATE
<?php
// This bootstrap file was generated by koharness. Use it to load the Kohana environment for your tests.
// It serves the same job that would be done by your index.php in a standard Kohana install.

// Define the Kohana environment
define('APPPATH', '$apppath');
define('MODPATH', '$modpath');
define('SYSPATH', '$syspath');
define('DOCROOT', '$docroot');
define('KOHARNESS_SRC', '$cwd/vendor/kohana/koharness/');
define('EXT', '.php');
if (PHP_VERSION_ID < 50400) {
  // Legacy behaviour (assumed unused) for consumers on 5.3.x
  error_reporting(E_ALL | E_STRICT);
} else {
  // For all versions >= 5.4.0, E_ALL is functionally identical to E_ALL | E_STRICT.
  error_reporting(E_ALL);
}
define('KOHANA_START_TIME', microtime(TRUE));
define('KOHANA_START_MEMORY', memory_get_usage());

// Require the application bootstrap
require(APPPATH.'bootstrap.php');

TEMPLATE;
return $template;
